import functools
import logging

from graphitesend.graphitesend import GraphiteSendException

logger = logging.getLogger("flask-graphite")


class Hook(object):
    """Represent a hook for flask requests

    A hook proxy calls to its function.

    :param function: The function used as hook
    :param type: The type of hook (before_request, after_request or
                 teardown_request)
    """

    def __init__(self, function, type="after_request"):
        self.function = function
        self.setup_hook = None
        self.type = type

    def __call__(self, response_or_exception=None):
        """Proxy for function calls"""
        if response_or_exception is None and self.is_setup_hook:
            return self.function()
        return self.function(response_or_exception)

    def __repr__(self):
        return "Hook({})".format(self.name)

    @property
    def name(self):
        return self.function.__name__

    __name__ = name

    @property
    def is_setup_hook(self):
        return self.type == "before_request"

    def setup(self, function):
        """Mark a function as a setup hook for this hook

        A setup hook is a hook required to run before its main hook. It's
        implemented as a before_request hook.

        :param function: The function used as setup hook
        """
        self.setup_hook = Hook(function, type="before_request")
        return self.setup_hook

    def register_into(self, obj, client):
        """Register the hook as a request hook in `obj`

        Can only be used on setup hooks. Bind the hook to a client for other
        types of hooks.

        :param obj: Either an application or a blueprint
        :param client: The client to use with this hook for this application
        """
        if self.setup_hook:
            self.setup_hook.register_into(obj, client)
        try:
            registering_method = getattr(obj, self.type)
        except AttributeError:
            logger.error("Invalid type \"%s\". Couldn't register \"%s\" "
                         "hook into %s.", self.type, self.name, obj)
            raise
        hook = self.make_application_hook(client)
        return registering_method(hook)

    def make_application_hook(self, client):
        """Make the hook into a flask registerable hook

        :oaram client: Where to send metrics generated by that application hook
        """
        @functools.wraps(self.function)
        def application_hook(*args):
            send_args = self(*args)
            if send_args is not None:
                try:
                    client.send(*send_args)
                except GraphiteSendException:  # pragma: no cover
                    logger.error("Couldn't send metric \"%s\"", send_args)
            if args:
                response = args[0]
                return response
        return application_hook
